apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qumulo-nfs-example
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: qumulo-nfs
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qumulo-smb-example
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: qumulo-smb
  resources:
    requests:
      storage: 10Gi
