{{- if .Values.csi.enabled }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.csi.driverName }}
  labels:
    {{- include "cosi-driver-qumulo.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: false
  fsGroupPolicy: None
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
{{- end }}
